local C = {}

C.GAME_W = 1280
C.GAME_H = 720

C.TILE = 32

-- Player
C.PLAYER_MAX_HP = 100
C.PLAYER_MAX_ENERGY = 100
C.PLAYER_ACCEL = 2800
C.PLAYER_FRICTION = 12
C.PLAYER_MAX_SPEED = 320
C.DASH_SPEED = 720
C.DASH_DURATION = 0.14
C.DASH_COOLDOWN = 1.1
C.ENERGY_REGEN = 8
C.DASH_ENERGY_COST = 22
C.SHOOT_COOLDOWN = 0.12
C.SHOOT_ENERGY_COST = 4
C.BULLET_SPEED = 560
C.BULLET_DAMAGE = 28
C.INVULN_TIME = 1.0

-- Enemies
C.PATROL_DRONE_HP = 45
C.HUNTER_DRONE_HP = 70
C.BASE_PATROL_SPEED = 90
C.BASE_HUNTER_PATROL_SPEED = 70
C.BASE_HUNT_SPEED = 140

-- Progression
C.NODES_TO_STABILIZE = 4
C.EVAC_DURATION = 18

-- Difficulty
C.DIFF_SPEED_PER_SEC = 0.08
C.DIFF_DETECT_PER_ROOM = 12
C.DIFF_SPAWN_BONUS = 0.35

return C
